name       : libsigrok
version    : 0.5.1
release    : 4
source     :
    - https://sigrok.org/download/source/libsigrok/libsigrok-0.5.1.tar.gz : e40fde7af98d29e922e9d3cbe0a6c0569889153fc31e47b8b1afe4d846292b9c
license    : GPL-3.0-or-later
component  : programming.library
summary    : Provides an API for communication with signal analyzer devices
description: |
    libsigrok is a shared library which provides the basic API for talking to various types of signal analyzers (such as logic analyzers, oscilloscopes, and multimeters) and reading/writing acquired data into various input/output file formats.
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libftdi1)
    - pkgconfig(libserialport)
    - pkgconfig(libzip)
    - bzip2-devel
    - doxygen
    - libieee1284-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm00755 contrib/60-libsigrok.rules $installdir/usr/lib64/udev/rules.d/61-libsigrok.rules
