name       : libsigrok
version    : 0.5.2
release    : 10
source     :
    - https://sigrok.org/download/source/libsigrok/libsigrok-0.5.2.tar.gz : 4d341f90b6220d3e8cb251dacf726c41165285612248f2c52d15df4590a1ce3c
license    : GPL-3.0-or-later
component  : programming.library
summary    : Provides an API for communication with signal analyzer devices
description: |
    libsigrok is a shared library which provides the basic API for talking to various types of signal analyzers (such as logic analyzers, oscilloscopes, and multimeters) and reading/writing acquired data into various input/output file formats.
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libftdi1)
    - pkgconfig(libserialport)
    - pkgconfig(libzip)
    - bzip2-devel
    - doxygen
    - libieee1284-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm00755 contrib/60-libsigrok.rules $installdir/usr/lib64/udev/rules.d/60-libsigrok.rules
    install -Dm00755 contrib/61-libsigrok-plugdev.rules $installdir/usr/lib64/udev/rules.d/61-libsigrok-plugdev.rules
    install -Dm00755 contrib/61-libsigrok-uaccess.rules $installdir/usr/lib64/udev/rules.d/61-libsigrok-uaccess.rules
