name       : libsigrok
version    : 0.5.0
release    : 2
source     :
    - http://sigrok.org/download/source/libsigrok/libsigrok-0.5.0.tar.gz : 4c8c86779b880a5c419f6c77a08b1147021e5a19fa83b0f3b19da27463c9f3a4
license    : GPL-3.0
component  : programming.library
summary    : Provides an API for communication with signal analyzer devices
description: |
    libsigrok is a shared library which provides the basic API for talking to various types of signal analyzers (such as logic analyzers, oscilloscopes, and multimeters) and reading/writing acquired data into various input/output file formats.
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libftdi1)
    - pkgconfig(libserialport)
    - pkgconfig(libzip)
    - bzip2-devel
    - doxygen
    - libieee1284-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -d $installdir/usr/lib64/udev/rules.d
    install -m755 $workdir/contrib/z60_libsigrok.rules $installdir/usr/lib64/udev/rules.d/61-libsigrok.rules
